# Generated by Django 4.2.7 on 2023-11-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_profile_options_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='quote',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=None, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
