# Generated by Django 4.2.7 on 2023-11-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
